import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-textGray`}>
        <header className="w-full flex items-center justify-between px-6 py-4 bg-backgroundAlt shadow-sm rounded-b-2xl">
          <div className="flex items-center gap-3">
            <span className="text-2xl font-bold text-textBlue tracking-tight">Insight Axis LLP</span>
          </div>
          <nav className="hidden md:flex gap-8 text-base font-medium">
            <a href="#services" className="hover:text-primary transition">Services</a>
            <a href="#industries" className="hover:text-primary transition">Industries</a>
            <a href="#why" className="hover:text-primary transition">Why Us</a>
            <a href="#contact" className="hover:text-primary transition">Contact</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
